# Generated by Django 4.2.17 on 2024-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='upload/avatars/'),
        ),
    ]
